image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$NOVUS_HEROKU_APP --api-key=$NOVUS_KEROKU_API_KEY
  only:
    - staging
